name: "PR Checks"
on:
  pull_request:
    types: [opened, edited, ready_for_review, reopened, synchronize]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: PR Check
        uses: pczern/verify-pr-action@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          descriptionRegex: "Description.+"
          titleMinLength: 10
          descriptionMinLength: 10
      - name: Get output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
